// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUo_MWEWpTF2o8qa_Ma4sQfvkXWApdZvQ',
    appId: '1:265839137932:web:e8aea86cc8594a14c897a9',
    messagingSenderId: '265839137932',
    projectId: 'flirt-dating-app-levels',
    authDomain: 'flirt-dating-app-levels.firebaseapp.com',
    storageBucket: 'flirt-dating-app-levels.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe5gzb7ESoRtBA4mapgSEHhkS4pMVQ9no',
    appId: '1:265839137932:android:f68a815a9390f581c897a9',
    messagingSenderId: '265839137932',
    projectId: 'flirt-dating-app-levels',
    storageBucket: 'flirt-dating-app-levels.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKLEVheOaQ0XHraYxVnOJfzQboSRAvNtw',
    appId: '1:265839137932:ios:8e5d3c67b20f3da7c897a9',
    messagingSenderId: '265839137932',
    projectId: 'flirt-dating-app-levels',
    storageBucket: 'flirt-dating-app-levels.appspot.com',
    iosClientId: '265839137932-aesfqbk8uek49gonl0dd6gffv5cf0299.apps.googleusercontent.com',
    iosBundleId: 'com.levels.flirt',
  );
}
